#include<iostream>
#include<climits>
using namespace std;
void maximum_sum_subarray(int a[], int n){
    int current_sum = 0;
    int maximum_sum = 0;
    int s=0; 
    int e=0;
    
    int c_sum[n] ={0};
    
    c_sum[0] = a[0];
    for(int i=1; i<n; i++){
        c_sum[i] = c_sum[i-1] + a[i];
    }
    
    for(int i=0; i<n; i++){
        for(int j=i; j<n; j++){
            current_sum = 0;
            
            current_sum = c_sum[j] - c_sum[i-1];
            
            if(current_sum > maximum_sum){
                maximum_sum =current_sum;
                s=i;
                e=j;
            }
        }
    }
    
    cout << "Maximum sum is = " << maximum_sum << endl;
    cout << "maximum sum is generated by array  between indexes  " << s << " and  " << e << endl;
    
}
void print(int a[], int n){
    for(int i=0; i<n; i++){
        cout << a[i];
    }
    cout << endl;
}

int main(){
    int n;
    cin >> n;
    
    int a[n];
     
    for(int i=0; i<n; i++){
        cin >> a[i];
    }
    
    print(a,n);
    
    maximum_sum_subarray(a,n);
    
    return 0;
}
